BOARD_TAG    = uno
MONITOR_PORT  = /dev/ttyACM2
ARDUINO_LIBS = SCEL_MillisOverflow XBee Adafruit_MCP4725 Adafruit_INA219 Adafruit_BMP085 \
				DallasTemperature OneWire SHT1x Wire SoftwareSerial EEPROM

include Arduino.mk



